### ISSUE TITLE
Different colour for new tabs?

### ISSUE THREAD

**Issue by adrianmihalko** [connordelacruz/iterm2-tab-color#1]
Hi,

Do you have any idea how to set different colour for new tabs?

**Comment by connordelacruz** [comment]
Hey @adrianmihalko,

To clarify: are you wanting to set a unique color for each new tab? 

I think you could achieve this with a custom script, maybe storing the colors of active tabs in a file and randomly picking a different color when a session starts. Then add something to your `.bash_logout` script to remove the color associated with the tab session when it closes so that color can be available to future tabs.

**Comment by connordelacruz** [comment]
Closing this since it's been a hot minute
